name: Build Docker Image

on:
    push:
        branches: [main, dev]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker Image for Testing
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  # load: true
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build