name: Deploy to Docker Hub

on:
    workflow_run:
        workflows: ["Run Tests"]
        types:
            - completed
        branches: [main, dev]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Pull Built Image
              run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build

            - name: Tag the Docker Image
              run: |
                  docker tag ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest

            - name: Push to Docker Hub
              run: |
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest
