name: Docker deployment and testing

on:
    push:
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./BackEnd/Dockerfile
                  load: true # Necessary to load the built image into Docker's image cache for the test step.
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest

            - name: Run Tests
              run: |
                  docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest dotnet test

            - name: Push to Docker Hub
              if: success() # This ensures the push only happens if the tests pass
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./BackEnd/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest
