name: Docker build, test, and deploy

on:
    push:
        branches: [main, dev]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  load: true # This will load the built image into Docker's image cache.
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

            - name: Run Tests in the Docker Container
              run: |
                  docker run --name backend_test_container -d ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest
                  docker exec backend_test_container dotnet test /app/BackEndTests
                  docker stop backend_test_container
                  docker rm backend_test_container

            - name: Push to Docker Hub
              if: success() # Only push if the tests pass
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest
