name: Docker build, test, and deploy

on:
    push:
        branches: [main, dev]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build the Docker images
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./BackEnd/Dockerfile
                  load: true # This will load the built images into Docker's image cache.
                  tags: user_microservice:build, user_microservice:latest

            - name: Run Tests
              run: |
                  docker run --name testcontainer user_microservice:build
                  docker rm testcontainer

            - name: Push the Docker image
              if: success() # Only push if the tests pass
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./BackEnd/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:latest
                  target: final
