name: Super Linter

on:
    push:
        branches-ignore: [main]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        name: Super Linter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Super Linter
              uses: github/super-linter@v3
              env:
                  VALIDATE_ALL_CODEBASE: false
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
