name: Build and Push Test Image

on:
  push:
    branches: [main, dev]

jobs:
  build_and_push_test_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker Image for Testing
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.Test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice_tests:latest
