name: Run Tests

on:
    workflow_run:
        workflows: ["Build Docker Image"]
        branches: [main, dev]
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Pull Docker Image for Testing
              run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build

            - name: Run Tests
              run: |
                  docker run --name backend_test_container ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build
                  docker logs backend_test_container
                  docker rm backend_test_container

            - name: Explicitly Run Tests
              run: |
                  docker run --name backend_test_container -d ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:test
                  docker exec backend_test_container dotnet test /src/BackEndTests --no-build -c Release --logger "console;verbosity=normal"
                  docker stop backend_test_container
                  docker rm backend_test_container
