name: Run Tests

on:
    workflow_run:
        workflows: ["Build Docker Image"]
        branches: [main, dev]
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Pull Docker Image for Testing
              run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build

            - name: Run Tests in Docker Container
              run: |
                  docker run --name test_container ${{ secrets.DOCKERHUB_USERNAME }}/user_microservice:build
                  docker rm test_container
